### ISSUE TITLE
[ E @ ConfigAssist.cpp:1236] Failed to load: /minimal.ini, sz: 0 B

### ISSUE THREAD

**Issue by carvalho-oak** [gemi254/ConfigAssist-ESP32-ESP8266#4]
Using a Nodemcu v2 and the example ConfigAssist-Minimal and getting this error:
**[ E @ ConfigAssist.cpp:1236] Failed to load: /minimal.ini, sz: 0 B**

Used the conf.deleteConfig() to reset everything and this is the serial output after starting it.

Installing log
`. Variables and constants in RAM (global, static), used 37996 / 80192 bytes (47%)
║   SEGMENT  BYTES    DESCRIPTION
╠══ DATA     1612     initialized variables
╠══ RODATA   9816     constants       
╚══ BSS      26568    zeroed variables
. Instruction RAM (IRAM_ATTR, ICACHE_RAM_ATTR), used 62011 / 65536 bytes (94%)
║   SEGMENT  BYTES    DESCRIPTION
╠══ ICACHE   32768    reserved space for flash instruction cache
╚══ IRAM     29243    code in IRAM    
. Code in flash (default, ICACHE_FLASH_ATTR), used 392188 / 1048576 bytes (37%)
║   SEGMENT  BYTES    DESCRIPTION
╚══ IROM     392188   code in flash   
esptool.py v3.0
Serial port /dev/cu.usbserial-0001
Connecting....
Chip is ESP8266EX
Features: WiFi
Crystal is 26MHz
MAC: 08:f9:e0:75:e2:02
Uploading stub...
Running stub...
Stub running...
Configuring flash size...
Auto-detected Flash size: 4MB
Compressed 437008 bytes to 303226...
Writing at 0x00000000... (5 %)
Writing at 0x00004000... (10 %)
Writing at 0x00008000... (15 %)
Writing at 0x0000c000... (21 %)
Writing at 0x00010000... (26 %)
Writing at 0x00014000... (31 %)
Writing at 0x00018000... (36 %)
Writing at 0x0001c000... (42 %)
Writing at 0x00020000... (47 %)
Writing at 0x00024000... (52 %)
Writing at 0x00028000... (57 %)
Writing at 0x0002c000... (63 %)
Writing at 0x00030000... (68 %)
Writing at 0x00034000... (73 %)
Writing at 0x00038000... (78 %)
Writing at 0x0003c000... (84 %)
Writing at 0x00040000... (89 %)
Writing at 0x00044000... (94 %)
Writing at 0x00048000... (100 %)
Wrote 437008 bytes (303226 compressed) at 0x00000000 in 26.8 seconds (effective 130.5 kbit/s)...
Hash of data verified.

Leaving...
Hard resetting via RTS pin...
`

Serial Monitor:
`rll�r$�n�l�b|���rb�b�nnlnnbbp�$blrlp�n0�l�bn�n��b��nn'l�l`�nnl`nr���nbl�`p�n�r�bbn�nb��nn'l`�nnl`nr���nb�`r��nb�`��$bl`��n�`��n�r��n|�l�l`bbrl�nb�nl`�rl�l�
SDK:2.2.2-dev(38a443e)/Core:3.1.2=30102000/lwIP:STABLE-2_1_3_RELEASE/glue:1.2-65-g06164fb/BearSSL:b024386

ESP8266
[ I @ ConfigAssist-Minimal.ino:25] Starting..
[ E @ ConfigAssist.cpp:578] File: /minimal.ini not exists!
[ I @ ConfigAssist.cpp:81] Config not found! Generating default..
fpm close 1 
mode : sta(08:f9:e0:75:e2:02) + softAP(0a:f9:e0:75:e2:02)
add if0
add if1
dhcp server start:(ip:192.168.4.1,mask:255.255.255.0,gw:192.168.4.1)
bcn 100
bcn 0
`

**Comment by gemi254** [comment]
Hi
Actually this is a warning meaning that this file is not in spiffs and a new one will be generated..
As far as i can see from your log file an access point is enabled..
dhcp server start:(ip:192.168.4.1,mask:255.255.255.0,gw:192.168.4.1)
Connect to the AP (configAssist_e075e202 to supply your SSID, PASS and everything will be ok.

Log messages from
fpm close 1
...
bcn 0
are displayed because you have enabled DCORE_DEBUG_LEVEL.

This is a log from my Nodemcu v2 ..

[ I @ ConfigAssist-Minimal.ino:23] Starting..
[ E @ ConfigAssist.cpp:578] File: /minimal.ini not exists!
[ I @ ConfigAssist.cpp:81] Config not found! Generating default..
[ I @ ConfigAssist.cpp:111] Wifi AP SSID: configAssist_7FE039 started, use 'http://192.168.4.1' to connect
[ E @ ConfigAssist-Minimal.ino:35] Connect failed.

**Comment by carvalho-oak** [comment]
Only happens on ESP8266, it works on ESP32.
